name: jedit
base: core24
version: "20.0.0"
summary: jedit is an MS-DOS inspired text editor
description: |
  jedit is a fork of Edit. It pays homage to the classic MS-DOS Editor, but with a modern interface and input controls similar to VS Code. Learn more at https://github.com/philip-flop/edit

grade: stable
confinement: strict

apps:
  jedit:
    command: bin/jedit
    plugs:
      - home

parts:
  edit:
    source: https://github.com/philip-flop/edit.git
    source-type: git
    plugin: rust
    build-packages:
      - build-essential
