.TH JEDIT 1 "version 20.0.0"
.SH NAME
jedit \- a simple text editor based on MS Edit
.SH SYNOPSIS
\fBjedit\fP [\fIOPTIONS\fP]... [\fIARGUMENTS\fP]...
.SH DESCRIPTION
jedit is a simple text editor based on MS Edit.
.SH EDITING
JEdit is an interactive mode-less editor. Use F10 to access the menus.
.SH ARGUMENTS
.TP
\fIFILE[:LINE[:COLUMN]]\fP
The file to open, optionally with line and column (e.g., \fBfoo.txt:123:45\fP).
.SH OPTIONS
.TP
\fB\-h\fP, \fB\-\-help\fP
Print the help message.
.TP
\fB\-v\fP, \fB\-\-version\fP
Print the version number.
.SH COPYRIGHT
Copyright \(co Microsoft Corporation.
.br
Licensed under the MIT License.
.SH SEE ALSO
.UR https://github.com/philip-flop/edit
.UE
.br
.UR https://github.com/microsoft/edit
.UE
